name: Release instarepo

on:
  push:
    tags: [ "v*" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Test with pytest
        run: |
          pipenv run pytest
      - name: Build wheel
        run: |
          pipenv run python -m build
      - name: Publish wheel with twine
        run: >
          pipenv run twine upload
          -u ${{secrets.INSTAREPO_TWINE_USERNAME}}
          -p ${{secrets.INSTAREPO_TWINE_PASSWORD}}
          --non-interactive
          --disable-progress-bar
          dist/*
